"""cria tabela registros

Revision ID: 5ea7424fd57f
Revises: 
Create Date: 2026-05-11 18:52:35.985240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea7424fd57f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel_foco', sa.Integer(), nullable=False),
    sa.Column('tempo_minutos', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_id'), 'registros', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_id'), table_name='registros')
    op.drop_table('registros')
    # ### end Alembic commands ###
